In [1]:
import os

import pandas as pd

In [2]:
INPUT_DIR = "/n/groups/kirschner/Will/BedRest"

## Nextflow preparation

In [3]:
sra_metadata = pd.read_csv(os.path.join(INPUT_DIR, "nfcore_rnaseq_3.14.0", "sra_explorer_metadata.tsv"), sep="\t")
sra_metadata

,Accession,Title,Platform,Total bases,Create date,SRA URL,SRA filename,SRA nice filename,FastQ URL,FastQ Aspera URL,FastQ filename,FastQ nice filename
0,SRR15503382,GSM5526415: D1 POST; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,57505,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503382.sra,SRR15503382_GSM5526415_D1_POST_Homo_sapiens_RN...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/082/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503382_1.fastq.gz,SRR15503382_GSM5526415_D1_POST_Homo_sapiens_RN...
1,SRR15503382,GSM5526415: D1 POST; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,57505,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503382.sra,SRR15503382_GSM5526415_D1_POST_Homo_sapiens_RN...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/082/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503382_2.fastq.gz,SRR15503382_GSM5526415_D1_POST_Homo_sapiens_RN...
2,SRR15503384,GSM5526417: E1 POST; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,45788,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503384.sra,SRR15503384_GSM5526417_E1_POST_Homo_sapiens_RN...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/084/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503384_1.fastq.gz,SRR15503384_GSM5526417_E1_POST_Homo_sapiens_RN...
3,SRR15503384,GSM5526417: E1 POST; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,45788,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503384.sra,SRR15503384_GSM5526417_E1_POST_Homo_sapiens_RN...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/084/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503384_2.fastq.gz,SRR15503384_GSM5526417_E1_POST_Homo_sapiens_RN...
4,SRR15503379,GSM5526412: B2 POST; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,60524,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503379.sra,SRR15503379_GSM5526412_B2_POST_Homo_sapiens_RN...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/079/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503379_1.fastq.gz,SRR15503379_GSM5526412_B2_POST_Homo_sapiens_RN...
...,...,...,...,...,...,...,...,...,...,...,...,...
75,SRR15503399,GSM5526432: B2 PRE; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,48496,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503399.sra,SRR15503399_GSM5526432_B2_PRE_Homo_sapiens_RNA...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/099/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503399_2.fastq.gz,SRR15503399_GSM5526432_B2_PRE_Homo_sapiens_RNA...
76,SRR15503401,GSM5526434: C2 PRE; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,49150,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503401.sra,SRR15503401_GSM5526434_C2_PRE_Homo_sapiens_RNA...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/001/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503401_1.fastq.gz,SRR15503401_GSM5526434_C2_PRE_Homo_sapiens_RNA...
77,SRR15503401,GSM5526434: C2 PRE; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,49150,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503401.sra,SRR15503401_GSM5526434_C2_PRE_Homo_sapiens_RNA...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/001/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503401_2.fastq.gz,SRR15503401_GSM5526434_C2_PRE_Homo_sapiens_RNA...
78,SRR15503400,GSM5526433: C1 PRE; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,51438,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503400.sra,SRR15503400_GSM5526433_C1_PRE_Homo_sapiens_RNA...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/000/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503400_1.fastq.gz,SRR15503400_GSM5526433_C1_PRE_Homo_sapiens_RNA...
79,SRR15503400,GSM5526433: C1 PRE; Homo sapiens; RNA-Seq,Illumina HiSeq 4000,51438,1641099600000,ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-insta...,SRR15503400.sra,SRR15503400_GSM5526433_C1_PRE_Homo_sapiens_RNA...,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/000/...,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR155/...,SRR15503400_2.fastq.gz,SRR15503400_GSM5526433_C1_PRE_Homo_sapiens_RNA...

In [6]:
DATA_DIR = "/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/input"
samples = []

for sample_sra, sample in sra_metadata.groupby("Accession"):
    
    sample_name = sample["FastQ nice filename"].iloc[0].split(".")[0].rsplit("_", 1)[0]
    fastq1_fp = os.path.join(DATA_DIR, f"{sample_sra}_1.fastq.gz")
    fastq2_fp = os.path.join(DATA_DIR, f"{sample_sra}_2.fastq.gz")
    
    samples.append(
        {
            "sample": sample_name,
            "fastq_1": fastq1_fp,
            "fastq_2": fastq2_fp,
            "strandedness": "auto"
            
        }
    )

samples_df = pd.DataFrame(samples)

samples_df

,sample,fastq_1,fastq_2,strandedness
0,SRR15503376_GSM5526409_A1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
1,SRR15503377_GSM5526410_A2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
2,SRR15503378_GSM5526411_B1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
3,SRR15503379_GSM5526412_B2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
4,SRR15503380_GSM5526413_C1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
5,SRR15503381_GSM5526414_C2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
6,SRR15503382_GSM5526415_D1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
7,SRR15503383_GSM5526416_D2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
8,SRR15503384_GSM5526417_E1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
9,SRR15503385_GSM5526418_E2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
10,SRR15503386_GSM5526419_F1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
11,SRR15503387_GSM5526420_F2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
12,SRR15503388_GSM5526421_G1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
13,SRR15503389_GSM5526422_G2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
14,SRR15503390_GSM5526423_H1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
15,SRR15503391_GSM5526424_H2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
16,SRR15503392_GSM5526425_I1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
17,SRR15503393_GSM5526426_I2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
18,SRR15503394_GSM5526427_J1_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
19,SRR15503395_GSM5526428_J2_POST_Homo_sapiens_RN...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
20,SRR15503396_GSM5526429_A1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
21,SRR15503397_GSM5526430_A2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
22,SRR15503398_GSM5526431_B1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
23,SRR15503399_GSM5526432_B2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
24,SRR15503400_GSM5526433_C1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
25,SRR15503401_GSM5526434_C2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
26,SRR15503402_GSM5526435_D1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
27,SRR15503403_GSM5526436_D2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
28,SRR15503404_GSM5526437_E1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
29,SRR15503405_GSM5526438_E2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
30,SRR15503406_GSM5526439_F1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
31,SRR15503407_GSM5526440_F2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
32,SRR15503408_GSM5526441_G1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
33,SRR15503409_GSM5526442_G2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
34,SRR15503410_GSM5526443_H1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
35,SRR15503411_GSM5526444_H2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
36,SRR15503412_GSM5526445_I1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
37,SRR15503413_GSM5526446_I2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
38,SRR15503414_GSM5526447_J1_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto
39,SRR15503415_GSM5526448_J2_PRE_Homo_sapiens_RNA...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,/n/scratch/users/w/wit498/bed_rest_bulkRNAseq/...,auto

In [7]:
samples_df.to_csv(os.path.join(INPUT_DIR, "samplesheet.csv"), index=False)

In [ ]:
sample,fastq_1,fastq_2,strandedness
CONTROL_REP1,AEG588A1_S1_L002_R1_001.fastq.gz,AEG588A1_S1_L002_R2_001.fastq.gz,auto
CONTROL_REP1,AEG588A1_S1_L003_R1_001.fastq.gz,AEG588A1_S1_L003_R2_001.fastq.gz,auto
CONTROL_REP1,AEG588A1_S1_L004_R1_001.fastq.gz,AEG588A1_S1_L004_R2_001.fastq.gz,auto

## Kallisto tximport

In [3]:
import glob

In [31]:
sample_fps = glob.glob(os.path.join(INPUT_DIR, "nfcore_rnaseq_3.14.0", "kallisto", "*", "abundance.h5"))
samples = pd.DataFrame({"filepath": sample_fps, })
samples[["patient", "tmp"]] = samples.filepath.str.rsplit("_", expand=True, n=5).iloc[:,[1, 2]]
samples

                                             filepath patient   tmp
0   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A1  POST
1   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A2  POST
2   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B1  POST
3   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B2  POST
4   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C1  POST
5   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C2  POST
6   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D1  POST
7   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D2  POST
8   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E1  POST
9   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E2  POST
10  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F1  POST
11  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F2  POST
12  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G1  POST
13  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G2  POST
14  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H1  POST
15  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H2  POST
16  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I1  POST
17  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I2  POST
18  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J1  POST
19  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J2  POST
20  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A1   PRE
21  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A2   PRE
22  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B1   PRE
23  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B2   PRE
24  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C1   PRE
25  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C2   PRE
26  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D1   PRE
27  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D2   PRE
28  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E1   PRE
29  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E2   PRE
30  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F1   PRE
31  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F2   PRE
32  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G1   PRE
33  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G2   PRE
34  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H1   PRE
35  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H2   PRE
36  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I1   PRE
37  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I2   PRE
38  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J1   PRE
39  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J2   PRE

In [32]:
samples.loc[samples.tmp == "POST", "tmp"] = "Post"
samples.loc[samples.tmp == "PRE", "tmp"] = "Pre"

In [19]:
sample_annot = pd.read_csv(os.path.join(INPUT_DIR, "samples.csv"))
sample_annot

,name,patient,tmp,group,total,n_genes_by_counts,total_counts,total_counts_rprot,pct_counts_rprot,total_counts_rRNA,pct_counts_rRNA,total_counts_mt,pct_counts_mt,tmp:group,FFA (mmol/l) Arter.,TAG (mmol/l) Arter.,INS (mIU/l) Arter.,Glucose (mmol/l) Arter.,GD mg/kg/min,Insulin (mIU/l) Venous
0,Pre_A1_Pre_BR_289105.bam,A1,Pre,Cocktail,49269604,28411,49269604,1391011,2.823264,6437,0.013065,10257548,20.819222,Pre:Cocktail,0.4150,0.58,4.697732,4.3,8.520406,2.8600
1,Pre_A2_Pre_BR_203130.bam,A2,Pre,Control,51010613,29593,51010613,1101490,2.159335,6814,0.013358,8698360,17.052059,Pre:Control,0.4795,0.94,21.947574,4.4,7.820128,7.1990
2,Pre_B1_Pre_BR_290117.bam,B1,Pre,Cocktail,43730612,29074,43730612,1247977,2.853784,5730,0.013103,7576403,17.325170,Pre:Cocktail,0.3902,0.46,5.902004,4.2,6.175030,3.2250
3,Pre_B2_Pre_BR_204142.bam,B2,Pre,Control,48593125,29644,48593125,923150,1.899754,7163,0.014741,8053423,16.573174,Pre:Control,0.4023,0.46,26.112456,4.6,7.417069,4.5270
4,Pre_C1_Pre_BR_291129.bam,C1,Pre,Control,51935425,29823,51935425,1143645,2.202052,7093,0.013657,8809183,16.961800,Pre:Control,0.5538,0.51,12.620836,4.3,6.301969,3.6185
5,Pre_C2_Pre_BR_205154.bam,C2,Pre,Cocktail,50054273,29123,50054273,1084242,2.166133,6959,0.013903,7902793,15.788448,Pre:Cocktail,0.2767,0.42,22.460194,4.1,6.683051,3.6575
6,Pre_D1_Pre_BR_292141.bam,D1,Pre,Control,47371511,28971,47371511,1020863,2.155015,5900,0.012455,10255908,21.649949,Pre:Control,0.9491,0.40,12.573115,4.6,4.914221,6.6300
7,Pre_D2_Pre_BR_206166.bam,D2,Pre,Control,46912722,29100,46912722,1347793,2.872980,5987,0.012762,10607772,22.611717,Pre:Control,0.4732,0.34,26.722870,4.3,7.504336,4.2795
8,Pre_E1_Pre_BR_293153.bam,E1,Pre,Control,50558345,29206,50558345,1264149,2.500377,7378,0.014593,8728047,17.263316,Pre:Control,0.4270,1.24,19.938857,4.4,5.444510,2.8600
9,Pre_E2_Pre_BR_207178.bam,E2,Pre,Cocktail,52668637,29527,52668637,1179858,2.240153,7297,0.013855,8390096,15.929966,Pre:Cocktail,0.3234,0.59,20.472952,4.1,7.110272,3.0645
10,Pre_F1_Pre_BR_294165.bam,F1,Pre,Cocktail,48451403,29338,48451403,1189422,2.454876,6817,0.014070,8102350,16.722632,Pre:Cocktail,0.4397,0.58,10.086931,4.5,6.601610,3.1050
11,Pre_F2_Pre_BR_208190.bam,F2,Pre,Cocktail,50626012,29264,50626012,1530065,3.022290,7437,0.014690,8111235,16.021872,Pre:Cocktail,0.2933,1.07,15.529665,4.0,10.675028,5.5720
12,Pre_G1_Pre_BR_295177.bam,G1,Pre,Cocktail,52345902,29407,52345902,1655829,3.163245,8105,0.015484,7268950,13.886378,Pre:Cocktail,0.4627,1.22,16.315768,4.5,6.776144,3.3970
13,Pre_G2_Pre_BR_209107.bam,G2,Pre,Control,51293259,29283,51293259,1129648,2.202332,6782,0.013222,10198605,19.882934,Pre:Control,0.4253,0.40,33.918688,4.1,9.998550,4.5370
14,Pre_H1_Pre_BR_296189.bam,H1,Pre,Control,51799883,28767,51799883,1779780,3.435876,7123,0.013751,10292354,19.869454,Pre:Control,0.4743,0.50,13.499287,4.4,7.521159,3.7120
15,Pre_H2_Pre_BR_210119.bam,H2,Pre,Cocktail,50753892,29222,50753892,1356609,2.672916,7465,0.014708,10107321,19.914376,Pre:Cocktail,0.4448,0.51,18.661565,4.1,8.878745,2.9045
16,Pre_I1_Pre_BR_201106.bam,I1,Pre,Cocktail,46385254,29999,46385254,1212978,2.615008,7172,0.015462,7041935,15.181409,Pre:Cocktail,0.3217,1.34,21.096212,4.5,5.610401,2.8600
17,Pre_I2_Pre_BR_211131.bam,I2,Pre,Cocktail,49561052,29351,49561052,1284697,2.592150,6178,0.012465,10378392,20.940621,Pre:Cocktail,0.2805,0.55,27.346620,4.3,8.058199,3.7080
18,Pre_J1_Pre_BR_202118.bam,J1,Pre,Control,52893287,29754,52893287,1128474,2.133492,6549,0.012382,10963227,20.727067,Pre:Control,0.5464,0.47,18.300000,4.9,7.679879,2.9045
19,Pre_J2_Pre_BR_212143.bam,J2,Pre,Control,49908866,29381,49908866,1236687,2.477890,6407,0.012837,8741068,17.514059,Pre:Control,0.2321,0.75,6.927000,4.4,9.234471,2.8600
20,Post_A1_Post_BR_213155.bam,A1,Post,Cocktail,53155055,28985,53155055,1395556,2.625444,7358,0.013843,9099034,17.117909,Post:Cocktail,0.3255,0.53,6.948525,4.1,6.356443,2.8600
21,Post_A2_Post_BR_223180.bam,A2,Post,Control,58326877,30483,58326877,1206269,2.068119,8301,0.014232,8845444,15.165297,Post:Control,0.4743,1.05,27.024653,4.5,5.838391,8.3850
22,Post_B1_Post_BR214167.bam,B1,Post,Cocktail,50912569,28804,50912569,1273257,2.500870,6996,0.013741,9715606,19.082922,Post:Cocktail,0.3702,0.53,12.066414,4.0,5.362148,3.7870
23,Post_B2_Post_BR_224192.bam,B2,Post,Control,59689860,30448,59689860,1334093,2.235041,8913,0.014932,10735478,17.985430,Post:Control,0.5710,0.46,19.189897,4.4,6.038004,6.7055
24,Post_C1_Post_BR_215179.bam,C1,Post,Control,45325045,28485,45325045,983943,2.170859,6167,0.013606,6944292,15.321092,Post:Control,0.3798,0.45,16.171171,4.3,4.586164,5.0915
25,Post_C2_Post_BR_225109.bam,C2,Post,Cocktail,51829041,29185,51829041,1155472,2.229391,6993,0.013492,8335087,16.081885,Post:Cocktail,0.4031,0.47,24.421308,4.1,5.539305,6.9100
26,Post_D1_Post_BR_216191.bam,D1,Post,Control,57155845,30321,57155845,1357521,2.375122,8112,0.014193,10065845,17.611226,Post:Control,1.0935,0.39,23.166643,4.9,3.994449,6.4245
27,Post_D2_Post_BR_226121.bam,D2,Post,Control,52418393,28925,52418393,1375822,2.624693,7722,0.014731,9737132,18.575793,Post:Control,0.4129,0.41,26.866961,4.3,5.905497,3.1765
28,Post_E1_Post_BR_217108.bam,E1,Post,Control,44863638,29595,44863638,1087266,2.423490,7159,0.015957,5406155,12.050193,Post:Control,0.4232,1.36,28.783098,4.4,4.195551,6.8660
29,Post_E2_Post_BR_227133.bam,E2,Post,Cocktail,46802669,29222,46802669,997099,2.130432,6202,0.013251,8615971,18.409145,Post:Cocktail,0.4303,0.52,21.549296,4.3,6.372336,3.6510
30,Post_F1_Post_BR_218120.bam,F1,Post,Cocktail,44694721,29492,44694721,999416,2.236094,6477,0.014492,7005787,15.674753,Post:Cocktail,0.3257,0.46,23.022846,4.7,4.823100,4.5000
31,Post_F2_Post_BR_228145.bam,F2,Post,Cocktail,52620200,29464,52620200,1273132,2.419474,7088,0.013470,9450853,17.960504,Post:Cocktail,0.3521,1.06,26.005122,4.0,6.018861,6.0465
32,Post_G1_Post_BR_219132.bam,G1,Post,Cocktail,46148816,29042,46148816,1136900,2.463552,6551,0.014195,6070111,13.153341,Post:Cocktail,0.3923,0.81,22.593106,4.3,5.906640,3.9840
33,Post_G2_Post_BR_229157.bam,G2,Post,Control,54451620,29407,54451620,1225712,2.251011,7893,0.014495,9382444,17.230789,Post:Control,0.4691,0.34,30.811222,5.0,5.903795,4.5055
34,Post_H1_Post_BR_220144.bam,H1,Post,Control,49500048,28363,49500048,1544192,3.119577,7002,0.014145,9523172,19.238713,Post:Control,0.3593,0.44,17.239043,4.1,5.782111,4.9035
35,Post_H2_Post_BR_230169.bam,H2,Post,Cocktail,53977387,29249,53977387,1217042,2.254726,7925,0.014682,9643474,17.865767,Post:Cocktail,0.6080,0.40,24.714442,4.0,5.917126,3.6900
36,Post_I1_Post_BR_221156.bam,I1,Post,Cocktail,51628243,30129,51628243,1091995,2.115112,7645,0.014808,9376117,18.160829,Post:Cocktail,0.3396,0.94,31.110192,4.8,5.388119,9.0330
37,Post_I2_Post_BR_231181.bam,I2,Post,Cocktail,46238449,28136,46238449,1803196,3.899776,7764,0.016791,10105233,21.854611,Post:Cocktail,0.3653,0.65,29.337093,4.6,6.005856,5.0955
38,Post_J1_Post_BR_222168.bam,J1,Post,Control,48876324,28897,48876324,967702,1.979899,6181,0.012646,11339068,23.199511,Post:Control,0.3361,0.64,20.988843,4.4,5.804417,9.7295
39,Post_J2_Post_BR_232193.bam,J2,Post,Control,53098461,28957,53098461,1572252,2.961012,7069,0.013313,9771890,18.403339,Post:Control,0.3167,0.88,13.285000,4.4,6.912927,2.8600

In [33]:
samples = samples.set_index(["patient", "tmp"]).join(sample_annot.set_index(["patient", "tmp"])).reset_index()
samples["sample_name"] = samples.patient + "_" + samples.tmp
samples

,patient,tmp,filepath,name,group,total,n_genes_by_counts,total_counts,total_counts_rprot,pct_counts_rprot,...,total_counts_mt,pct_counts_mt,tmp:group,FFA (mmol/l) Arter.,TAG (mmol/l) Arter.,INS (mIU/l) Arter.,Glucose (mmol/l) Arter.,GD mg/kg/min,Insulin (mIU/l) Venous,sample_name
0,A1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_A1_Post_BR_213155.bam,Cocktail,53155055,28985,53155055,1395556,2.625444,...,9099034,17.117909,Post:Cocktail,0.3255,0.53,6.948525,4.1,6.356443,2.8600,A1_Post
1,A2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_A2_Post_BR_223180.bam,Control,58326877,30483,58326877,1206269,2.068119,...,8845444,15.165297,Post:Control,0.4743,1.05,27.024653,4.5,5.838391,8.3850,A2_Post
2,B1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_B1_Post_BR214167.bam,Cocktail,50912569,28804,50912569,1273257,2.500870,...,9715606,19.082922,Post:Cocktail,0.3702,0.53,12.066414,4.0,5.362148,3.7870,B1_Post
3,B2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_B2_Post_BR_224192.bam,Control,59689860,30448,59689860,1334093,2.235041,...,10735478,17.985430,Post:Control,0.5710,0.46,19.189897,4.4,6.038004,6.7055,B2_Post
4,C1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_C1_Post_BR_215179.bam,Control,45325045,28485,45325045,983943,2.170859,...,6944292,15.321092,Post:Control,0.3798,0.45,16.171171,4.3,4.586164,5.0915,C1_Post
5,C2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_C2_Post_BR_225109.bam,Cocktail,51829041,29185,51829041,1155472,2.229391,...,8335087,16.081885,Post:Cocktail,0.4031,0.47,24.421308,4.1,5.539305,6.9100,C2_Post
6,D1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_D1_Post_BR_216191.bam,Control,57155845,30321,57155845,1357521,2.375122,...,10065845,17.611226,Post:Control,1.0935,0.39,23.166643,4.9,3.994449,6.4245,D1_Post
7,D2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_D2_Post_BR_226121.bam,Control,52418393,28925,52418393,1375822,2.624693,...,9737132,18.575793,Post:Control,0.4129,0.41,26.866961,4.3,5.905497,3.1765,D2_Post
8,E1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_E1_Post_BR_217108.bam,Control,44863638,29595,44863638,1087266,2.423490,...,5406155,12.050193,Post:Control,0.4232,1.36,28.783098,4.4,4.195551,6.8660,E1_Post
9,E2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_E2_Post_BR_227133.bam,Cocktail,46802669,29222,46802669,997099,2.130432,...,8615971,18.409145,Post:Cocktail,0.4303,0.52,21.549296,4.3,6.372336,3.6510,E2_Post
10,F1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_F1_Post_BR_218120.bam,Cocktail,44694721,29492,44694721,999416,2.236094,...,7005787,15.674753,Post:Cocktail,0.3257,0.46,23.022846,4.7,4.823100,4.5000,F1_Post
11,F2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_F2_Post_BR_228145.bam,Cocktail,52620200,29464,52620200,1273132,2.419474,...,9450853,17.960504,Post:Cocktail,0.3521,1.06,26.005122,4.0,6.018861,6.0465,F2_Post
12,G1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_G1_Post_BR_219132.bam,Cocktail,46148816,29042,46148816,1136900,2.463552,...,6070111,13.153341,Post:Cocktail,0.3923,0.81,22.593106,4.3,5.906640,3.9840,G1_Post
13,G2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_G2_Post_BR_229157.bam,Control,54451620,29407,54451620,1225712,2.251011,...,9382444,17.230789,Post:Control,0.4691,0.34,30.811222,5.0,5.903795,4.5055,G2_Post
14,H1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_H1_Post_BR_220144.bam,Control,49500048,28363,49500048,1544192,3.119577,...,9523172,19.238713,Post:Control,0.3593,0.44,17.239043,4.1,5.782111,4.9035,H1_Post
15,H2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_H2_Post_BR_230169.bam,Cocktail,53977387,29249,53977387,1217042,2.254726,...,9643474,17.865767,Post:Cocktail,0.6080,0.40,24.714442,4.0,5.917126,3.6900,H2_Post
16,I1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_I1_Post_BR_221156.bam,Cocktail,51628243,30129,51628243,1091995,2.115112,...,9376117,18.160829,Post:Cocktail,0.3396,0.94,31.110192,4.8,5.388119,9.0330,I1_Post
17,I2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_I2_Post_BR_231181.bam,Cocktail,46238449,28136,46238449,1803196,3.899776,...,10105233,21.854611,Post:Cocktail,0.3653,0.65,29.337093,4.6,6.005856,5.0955,I2_Post
18,J1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_J1_Post_BR_222168.bam,Control,48876324,28897,48876324,967702,1.979899,...,11339068,23.199511,Post:Control,0.3361,0.64,20.988843,4.4,5.804417,9.7295,J1_Post
19,J2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_J2_Post_BR_232193.bam,Control,53098461,28957,53098461,1572252,2.961012,...,9771890,18.403339,Post:Control,0.3167,0.88,13.285000,4.4,6.912927,2.8600,J2_Post
20,A1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_A1_Pre_BR_289105.bam,Cocktail,49269604,28411,49269604,1391011,2.823264,...,10257548,20.819222,Pre:Cocktail,0.4150,0.58,4.697732,4.3,8.520406,2.8600,A1_Pre
21,A2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_A2_Pre_BR_203130.bam,Control,51010613,29593,51010613,1101490,2.159335,...,8698360,17.052059,Pre:Control,0.4795,0.94,21.947574,4.4,7.820128,7.1990,A2_Pre
22,B1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_B1_Pre_BR_290117.bam,Cocktail,43730612,29074,43730612,1247977,2.853784,...,7576403,17.325170,Pre:Cocktail,0.3902,0.46,5.902004,4.2,6.175030,3.2250,B1_Pre
23,B2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_B2_Pre_BR_204142.bam,Control,48593125,29644,48593125,923150,1.899754,...,8053423,16.573174,Pre:Control,0.4023,0.46,26.112456,4.6,7.417069,4.5270,B2_Pre
24,C1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_C1_Pre_BR_291129.bam,Control,51935425,29823,51935425,1143645,2.202052,...,8809183,16.961800,Pre:Control,0.5538,0.51,12.620836,4.3,6.301969,3.6185,C1_Pre
25,C2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_C2_Pre_BR_205154.bam,Cocktail,50054273,29123,50054273,1084242,2.166133,...,7902793,15.788448,Pre:Cocktail,0.2767,0.42,22.460194,4.1,6.683051,3.6575,C2_Pre
26,D1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_D1_Pre_BR_292141.bam,Control,47371511,28971,47371511,1020863,2.155015,...,10255908,21.649949,Pre:Control,0.9491,0.40,12.573115,4.6,4.914221,6.6300,D1_Pre
27,D2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_D2_Pre_BR_206166.bam,Control,46912722,29100,46912722,1347793,2.872980,...,10607772,22.611717,Pre:Control,0.4732,0.34,26.722870,4.3,7.504336,4.2795,D2_Pre
28,E1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_E1_Pre_BR_293153.bam,Control,50558345,29206,50558345,1264149,2.500377,...,8728047,17.263316,Pre:Control,0.4270,1.24,19.938857,4.4,5.444510,2.8600,E1_Pre
29,E2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_E2_Pre_BR_207178.bam,Cocktail,52668637,29527,52668637,1179858,2.240153,...,8390096,15.929966,Pre:Cocktail,0.3234,0.59,20.472952,4.1,7.110272,3.0645,E2_Pre
30,F1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_F1_Pre_BR_294165.bam,Cocktail,48451403,29338,48451403,1189422,2.454876,...,8102350,16.722632,Pre:Cocktail,0.4397,0.58,10.086931,4.5,6.601610,3.1050,F1_Pre
31,F2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_F2_Pre_BR_208190.bam,Cocktail,50626012,29264,50626012,1530065,3.022290,...,8111235,16.021872,Pre:Cocktail,0.2933,1.07,15.529665,4.0,10.675028,5.5720,F2_Pre
32,G1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_G1_Pre_BR_295177.bam,Cocktail,52345902,29407,52345902,1655829,3.163245,...,7268950,13.886378,Pre:Cocktail,0.4627,1.22,16.315768,4.5,6.776144,3.3970,G1_Pre
33,G2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_G2_Pre_BR_209107.bam,Control,51293259,29283,51293259,1129648,2.202332,...,10198605,19.882934,Pre:Control,0.4253,0.40,33.918688,4.1,9.998550,4.5370,G2_Pre
34,H1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_H1_Pre_BR_296189.bam,Control,51799883,28767,51799883,1779780,3.435876,...,10292354,19.869454,Pre:Control,0.4743,0.50,13.499287,4.4,7.521159,3.7120,H1_Pre
35,H2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_H2_Pre_BR_210119.bam,Cocktail,50753892,29222,50753892,1356609,2.672916,...,10107321,19.914376,Pre:Cocktail,0.4448,0.51,18.661565,4.1,8.878745,2.9045,H2_Pre
36,I1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_I1_Pre_BR_201106.bam,Cocktail,46385254,29999,46385254,1212978,2.615008,...,7041935,15.181409,Pre:Cocktail,0.3217,1.34,21.096212,4.5,5.610401,2.8600,I1_Pre
37,I2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_I2_Pre_BR_211131.bam,Cocktail,49561052,29351,49561052,1284697,2.592150,...,10378392,20.940621,Pre:Cocktail,0.2805,0.55,27.346620,4.3,8.058199,3.7080,I2_Pre
38,J1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_J1_Pre_BR_202118.bam,Control,52893287,29754,52893287,1128474,2.133492,...,10963227,20.727067,Pre:Control,0.5464,0.47,18.300000,4.9,7.679879,2.9045,J1_Pre
39,J2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_J2_Pre_BR_212143.bam,Control,49908866,29381,49908866,1236687,2.477890,...,8741068,17.514059,Pre:Control,0.2321,0.75,6.927000,4.4,9.234471,2.8600,J2_Pre

In [35]:
samples.to_csv(os.path.join(INPUT_DIR, "samples_tximport.csv"), index=False)

In [36]:
os.path.join(INPUT_DIR, "samples_tximport.csv")

'/n/groups/kirschner/Will/BedRest/samples_tximport.csv'

## STAR-RSEM tximport

In [3]:
import glob

In [4]:
sample_fps = glob.glob(os.path.join(INPUT_DIR, "nfcore_rnaseq_3.14.0", "star_rsem", "*.isoforms.results"))
samples = pd.DataFrame({"filepath": sample_fps, })
samples[["patient", "tmp"]] = samples.filepath.str.rsplit("_", expand=True, n=5).iloc[:,[1, 2]]
samples

                                             filepath patient   tmp
0   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A1  POST
1   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A2  POST
2   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B1  POST
3   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B2  POST
4   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C1  POST
5   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C2  POST
6   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D1  POST
7   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D2  POST
8   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E1  POST
9   /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E2  POST
10  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F1  POST
11  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F2  POST
12  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G1  POST
13  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G2  POST
14  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H1  POST
15  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H2  POST
16  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I1  POST
17  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I2  POST
18  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J1  POST
19  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J2  POST
20  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A1   PRE
21  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      A2   PRE
22  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B1   PRE
23  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      B2   PRE
24  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C1   PRE
25  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      C2   PRE
26  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D1   PRE
27  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      D2   PRE
28  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E1   PRE
29  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      E2   PRE
30  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F1   PRE
31  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      F2   PRE
32  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G1   PRE
33  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      G2   PRE
34  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H1   PRE
35  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      H2   PRE
36  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I1   PRE
37  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      I2   PRE
38  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J1   PRE
39  /n/groups/kirschner/Will/BedRest/nfcore_rnaseq...      J2   PRE

In [6]:
samples.loc[samples.tmp == "POST", "tmp"] = "Post"
samples.loc[samples.tmp == "PRE", "tmp"] = "Pre"

In [7]:
sample_annot = pd.read_csv(os.path.join(INPUT_DIR, "samples.csv"))
sample_annot

,name,patient,tmp,group,total,n_genes_by_counts,total_counts,total_counts_rprot,pct_counts_rprot,total_counts_rRNA,pct_counts_rRNA,total_counts_mt,pct_counts_mt,tmp:group,FFA (mmol/l) Arter.,TAG (mmol/l) Arter.,INS (mIU/l) Arter.,Glucose (mmol/l) Arter.,GD mg/kg/min,Insulin (mIU/l) Venous
0,Pre_A1_Pre_BR_289105.bam,A1,Pre,Cocktail,49269604,28411,49269604,1391011,2.823264,6437,0.013065,10257548,20.819222,Pre:Cocktail,0.4150,0.58,4.697732,4.3,8.520406,2.8600
1,Pre_A2_Pre_BR_203130.bam,A2,Pre,Control,51010613,29593,51010613,1101490,2.159335,6814,0.013358,8698360,17.052059,Pre:Control,0.4795,0.94,21.947574,4.4,7.820128,7.1990
2,Pre_B1_Pre_BR_290117.bam,B1,Pre,Cocktail,43730612,29074,43730612,1247977,2.853784,5730,0.013103,7576403,17.325170,Pre:Cocktail,0.3902,0.46,5.902004,4.2,6.175030,3.2250
3,Pre_B2_Pre_BR_204142.bam,B2,Pre,Control,48593125,29644,48593125,923150,1.899754,7163,0.014741,8053423,16.573174,Pre:Control,0.4023,0.46,26.112456,4.6,7.417069,4.5270
4,Pre_C1_Pre_BR_291129.bam,C1,Pre,Control,51935425,29823,51935425,1143645,2.202052,7093,0.013657,8809183,16.961800,Pre:Control,0.5538,0.51,12.620836,4.3,6.301969,3.6185
5,Pre_C2_Pre_BR_205154.bam,C2,Pre,Cocktail,50054273,29123,50054273,1084242,2.166133,6959,0.013903,7902793,15.788448,Pre:Cocktail,0.2767,0.42,22.460194,4.1,6.683051,3.6575
6,Pre_D1_Pre_BR_292141.bam,D1,Pre,Control,47371511,28971,47371511,1020863,2.155015,5900,0.012455,10255908,21.649949,Pre:Control,0.9491,0.40,12.573115,4.6,4.914221,6.6300
7,Pre_D2_Pre_BR_206166.bam,D2,Pre,Control,46912722,29100,46912722,1347793,2.872980,5987,0.012762,10607772,22.611717,Pre:Control,0.4732,0.34,26.722870,4.3,7.504336,4.2795
8,Pre_E1_Pre_BR_293153.bam,E1,Pre,Control,50558345,29206,50558345,1264149,2.500377,7378,0.014593,8728047,17.263316,Pre:Control,0.4270,1.24,19.938857,4.4,5.444510,2.8600
9,Pre_E2_Pre_BR_207178.bam,E2,Pre,Cocktail,52668637,29527,52668637,1179858,2.240153,7297,0.013855,8390096,15.929966,Pre:Cocktail,0.3234,0.59,20.472952,4.1,7.110272,3.0645
10,Pre_F1_Pre_BR_294165.bam,F1,Pre,Cocktail,48451403,29338,48451403,1189422,2.454876,6817,0.014070,8102350,16.722632,Pre:Cocktail,0.4397,0.58,10.086931,4.5,6.601610,3.1050
11,Pre_F2_Pre_BR_208190.bam,F2,Pre,Cocktail,50626012,29264,50626012,1530065,3.022290,7437,0.014690,8111235,16.021872,Pre:Cocktail,0.2933,1.07,15.529665,4.0,10.675028,5.5720
12,Pre_G1_Pre_BR_295177.bam,G1,Pre,Cocktail,52345902,29407,52345902,1655829,3.163245,8105,0.015484,7268950,13.886378,Pre:Cocktail,0.4627,1.22,16.315768,4.5,6.776144,3.3970
13,Pre_G2_Pre_BR_209107.bam,G2,Pre,Control,51293259,29283,51293259,1129648,2.202332,6782,0.013222,10198605,19.882934,Pre:Control,0.4253,0.40,33.918688,4.1,9.998550,4.5370
14,Pre_H1_Pre_BR_296189.bam,H1,Pre,Control,51799883,28767,51799883,1779780,3.435876,7123,0.013751,10292354,19.869454,Pre:Control,0.4743,0.50,13.499287,4.4,7.521159,3.7120
15,Pre_H2_Pre_BR_210119.bam,H2,Pre,Cocktail,50753892,29222,50753892,1356609,2.672916,7465,0.014708,10107321,19.914376,Pre:Cocktail,0.4448,0.51,18.661565,4.1,8.878745,2.9045
16,Pre_I1_Pre_BR_201106.bam,I1,Pre,Cocktail,46385254,29999,46385254,1212978,2.615008,7172,0.015462,7041935,15.181409,Pre:Cocktail,0.3217,1.34,21.096212,4.5,5.610401,2.8600
17,Pre_I2_Pre_BR_211131.bam,I2,Pre,Cocktail,49561052,29351,49561052,1284697,2.592150,6178,0.012465,10378392,20.940621,Pre:Cocktail,0.2805,0.55,27.346620,4.3,8.058199,3.7080
18,Pre_J1_Pre_BR_202118.bam,J1,Pre,Control,52893287,29754,52893287,1128474,2.133492,6549,0.012382,10963227,20.727067,Pre:Control,0.5464,0.47,18.300000,4.9,7.679879,2.9045
19,Pre_J2_Pre_BR_212143.bam,J2,Pre,Control,49908866,29381,49908866,1236687,2.477890,6407,0.012837,8741068,17.514059,Pre:Control,0.2321,0.75,6.927000,4.4,9.234471,2.8600
20,Post_A1_Post_BR_213155.bam,A1,Post,Cocktail,53155055,28985,53155055,1395556,2.625444,7358,0.013843,9099034,17.117909,Post:Cocktail,0.3255,0.53,6.948525,4.1,6.356443,2.8600
21,Post_A2_Post_BR_223180.bam,A2,Post,Control,58326877,30483,58326877,1206269,2.068119,8301,0.014232,8845444,15.165297,Post:Control,0.4743,1.05,27.024653,4.5,5.838391,8.3850
22,Post_B1_Post_BR214167.bam,B1,Post,Cocktail,50912569,28804,50912569,1273257,2.500870,6996,0.013741,9715606,19.082922,Post:Cocktail,0.3702,0.53,12.066414,4.0,5.362148,3.7870
23,Post_B2_Post_BR_224192.bam,B2,Post,Control,59689860,30448,59689860,1334093,2.235041,8913,0.014932,10735478,17.985430,Post:Control,0.5710,0.46,19.189897,4.4,6.038004,6.7055
24,Post_C1_Post_BR_215179.bam,C1,Post,Control,45325045,28485,45325045,983943,2.170859,6167,0.013606,6944292,15.321092,Post:Control,0.3798,0.45,16.171171,4.3,4.586164,5.0915
25,Post_C2_Post_BR_225109.bam,C2,Post,Cocktail,51829041,29185,51829041,1155472,2.229391,6993,0.013492,8335087,16.081885,Post:Cocktail,0.4031,0.47,24.421308,4.1,5.539305,6.9100
26,Post_D1_Post_BR_216191.bam,D1,Post,Control,57155845,30321,57155845,1357521,2.375122,8112,0.014193,10065845,17.611226,Post:Control,1.0935,0.39,23.166643,4.9,3.994449,6.4245
27,Post_D2_Post_BR_226121.bam,D2,Post,Control,52418393,28925,52418393,1375822,2.624693,7722,0.014731,9737132,18.575793,Post:Control,0.4129,0.41,26.866961,4.3,5.905497,3.1765
28,Post_E1_Post_BR_217108.bam,E1,Post,Control,44863638,29595,44863638,1087266,2.423490,7159,0.015957,5406155,12.050193,Post:Control,0.4232,1.36,28.783098,4.4,4.195551,6.8660
29,Post_E2_Post_BR_227133.bam,E2,Post,Cocktail,46802669,29222,46802669,997099,2.130432,6202,0.013251,8615971,18.409145,Post:Cocktail,0.4303,0.52,21.549296,4.3,6.372336,3.6510
30,Post_F1_Post_BR_218120.bam,F1,Post,Cocktail,44694721,29492,44694721,999416,2.236094,6477,0.014492,7005787,15.674753,Post:Cocktail,0.3257,0.46,23.022846,4.7,4.823100,4.5000
31,Post_F2_Post_BR_228145.bam,F2,Post,Cocktail,52620200,29464,52620200,1273132,2.419474,7088,0.013470,9450853,17.960504,Post:Cocktail,0.3521,1.06,26.005122,4.0,6.018861,6.0465
32,Post_G1_Post_BR_219132.bam,G1,Post,Cocktail,46148816,29042,46148816,1136900,2.463552,6551,0.014195,6070111,13.153341,Post:Cocktail,0.3923,0.81,22.593106,4.3,5.906640,3.9840
33,Post_G2_Post_BR_229157.bam,G2,Post,Control,54451620,29407,54451620,1225712,2.251011,7893,0.014495,9382444,17.230789,Post:Control,0.4691,0.34,30.811222,5.0,5.903795,4.5055
34,Post_H1_Post_BR_220144.bam,H1,Post,Control,49500048,28363,49500048,1544192,3.119577,7002,0.014145,9523172,19.238713,Post:Control,0.3593,0.44,17.239043,4.1,5.782111,4.9035
35,Post_H2_Post_BR_230169.bam,H2,Post,Cocktail,53977387,29249,53977387,1217042,2.254726,7925,0.014682,9643474,17.865767,Post:Cocktail,0.6080,0.40,24.714442,4.0,5.917126,3.6900
36,Post_I1_Post_BR_221156.bam,I1,Post,Cocktail,51628243,30129,51628243,1091995,2.115112,7645,0.014808,9376117,18.160829,Post:Cocktail,0.3396,0.94,31.110192,4.8,5.388119,9.0330
37,Post_I2_Post_BR_231181.bam,I2,Post,Cocktail,46238449,28136,46238449,1803196,3.899776,7764,0.016791,10105233,21.854611,Post:Cocktail,0.3653,0.65,29.337093,4.6,6.005856,5.0955
38,Post_J1_Post_BR_222168.bam,J1,Post,Control,48876324,28897,48876324,967702,1.979899,6181,0.012646,11339068,23.199511,Post:Control,0.3361,0.64,20.988843,4.4,5.804417,9.7295
39,Post_J2_Post_BR_232193.bam,J2,Post,Control,53098461,28957,53098461,1572252,2.961012,7069,0.013313,9771890,18.403339,Post:Control,0.3167,0.88,13.285000,4.4,6.912927,2.8600

In [8]:
samples = samples.set_index(["patient", "tmp"]).join(sample_annot.set_index(["patient", "tmp"])).reset_index()
samples["sample_name"] = samples.patient + "_" + samples.tmp
samples

,patient,tmp,filepath,name,group,total,n_genes_by_counts,total_counts,total_counts_rprot,pct_counts_rprot,...,total_counts_mt,pct_counts_mt,tmp:group,FFA (mmol/l) Arter.,TAG (mmol/l) Arter.,INS (mIU/l) Arter.,Glucose (mmol/l) Arter.,GD mg/kg/min,Insulin (mIU/l) Venous,sample_name
0,A1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_A1_Post_BR_213155.bam,Cocktail,53155055,28985,53155055,1395556,2.625444,...,9099034,17.117909,Post:Cocktail,0.3255,0.53,6.948525,4.1,6.356443,2.8600,A1_Post
1,A2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_A2_Post_BR_223180.bam,Control,58326877,30483,58326877,1206269,2.068119,...,8845444,15.165297,Post:Control,0.4743,1.05,27.024653,4.5,5.838391,8.3850,A2_Post
2,B1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_B1_Post_BR214167.bam,Cocktail,50912569,28804,50912569,1273257,2.500870,...,9715606,19.082922,Post:Cocktail,0.3702,0.53,12.066414,4.0,5.362148,3.7870,B1_Post
3,B2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_B2_Post_BR_224192.bam,Control,59689860,30448,59689860,1334093,2.235041,...,10735478,17.985430,Post:Control,0.5710,0.46,19.189897,4.4,6.038004,6.7055,B2_Post
4,C1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_C1_Post_BR_215179.bam,Control,45325045,28485,45325045,983943,2.170859,...,6944292,15.321092,Post:Control,0.3798,0.45,16.171171,4.3,4.586164,5.0915,C1_Post
5,C2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_C2_Post_BR_225109.bam,Cocktail,51829041,29185,51829041,1155472,2.229391,...,8335087,16.081885,Post:Cocktail,0.4031,0.47,24.421308,4.1,5.539305,6.9100,C2_Post
6,D1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_D1_Post_BR_216191.bam,Control,57155845,30321,57155845,1357521,2.375122,...,10065845,17.611226,Post:Control,1.0935,0.39,23.166643,4.9,3.994449,6.4245,D1_Post
7,D2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_D2_Post_BR_226121.bam,Control,52418393,28925,52418393,1375822,2.624693,...,9737132,18.575793,Post:Control,0.4129,0.41,26.866961,4.3,5.905497,3.1765,D2_Post
8,E1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_E1_Post_BR_217108.bam,Control,44863638,29595,44863638,1087266,2.423490,...,5406155,12.050193,Post:Control,0.4232,1.36,28.783098,4.4,4.195551,6.8660,E1_Post
9,E2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_E2_Post_BR_227133.bam,Cocktail,46802669,29222,46802669,997099,2.130432,...,8615971,18.409145,Post:Cocktail,0.4303,0.52,21.549296,4.3,6.372336,3.6510,E2_Post
10,F1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_F1_Post_BR_218120.bam,Cocktail,44694721,29492,44694721,999416,2.236094,...,7005787,15.674753,Post:Cocktail,0.3257,0.46,23.022846,4.7,4.823100,4.5000,F1_Post
11,F2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_F2_Post_BR_228145.bam,Cocktail,52620200,29464,52620200,1273132,2.419474,...,9450853,17.960504,Post:Cocktail,0.3521,1.06,26.005122,4.0,6.018861,6.0465,F2_Post
12,G1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_G1_Post_BR_219132.bam,Cocktail,46148816,29042,46148816,1136900,2.463552,...,6070111,13.153341,Post:Cocktail,0.3923,0.81,22.593106,4.3,5.906640,3.9840,G1_Post
13,G2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_G2_Post_BR_229157.bam,Control,54451620,29407,54451620,1225712,2.251011,...,9382444,17.230789,Post:Control,0.4691,0.34,30.811222,5.0,5.903795,4.5055,G2_Post
14,H1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_H1_Post_BR_220144.bam,Control,49500048,28363,49500048,1544192,3.119577,...,9523172,19.238713,Post:Control,0.3593,0.44,17.239043,4.1,5.782111,4.9035,H1_Post
15,H2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_H2_Post_BR_230169.bam,Cocktail,53977387,29249,53977387,1217042,2.254726,...,9643474,17.865767,Post:Cocktail,0.6080,0.40,24.714442,4.0,5.917126,3.6900,H2_Post
16,I1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_I1_Post_BR_221156.bam,Cocktail,51628243,30129,51628243,1091995,2.115112,...,9376117,18.160829,Post:Cocktail,0.3396,0.94,31.110192,4.8,5.388119,9.0330,I1_Post
17,I2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_I2_Post_BR_231181.bam,Cocktail,46238449,28136,46238449,1803196,3.899776,...,10105233,21.854611,Post:Cocktail,0.3653,0.65,29.337093,4.6,6.005856,5.0955,I2_Post
18,J1,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_J1_Post_BR_222168.bam,Control,48876324,28897,48876324,967702,1.979899,...,11339068,23.199511,Post:Control,0.3361,0.64,20.988843,4.4,5.804417,9.7295,J1_Post
19,J2,Post,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Post_J2_Post_BR_232193.bam,Control,53098461,28957,53098461,1572252,2.961012,...,9771890,18.403339,Post:Control,0.3167,0.88,13.285000,4.4,6.912927,2.8600,J2_Post
20,A1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_A1_Pre_BR_289105.bam,Cocktail,49269604,28411,49269604,1391011,2.823264,...,10257548,20.819222,Pre:Cocktail,0.4150,0.58,4.697732,4.3,8.520406,2.8600,A1_Pre
21,A2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_A2_Pre_BR_203130.bam,Control,51010613,29593,51010613,1101490,2.159335,...,8698360,17.052059,Pre:Control,0.4795,0.94,21.947574,4.4,7.820128,7.1990,A2_Pre
22,B1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_B1_Pre_BR_290117.bam,Cocktail,43730612,29074,43730612,1247977,2.853784,...,7576403,17.325170,Pre:Cocktail,0.3902,0.46,5.902004,4.2,6.175030,3.2250,B1_Pre
23,B2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_B2_Pre_BR_204142.bam,Control,48593125,29644,48593125,923150,1.899754,...,8053423,16.573174,Pre:Control,0.4023,0.46,26.112456,4.6,7.417069,4.5270,B2_Pre
24,C1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_C1_Pre_BR_291129.bam,Control,51935425,29823,51935425,1143645,2.202052,...,8809183,16.961800,Pre:Control,0.5538,0.51,12.620836,4.3,6.301969,3.6185,C1_Pre
25,C2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_C2_Pre_BR_205154.bam,Cocktail,50054273,29123,50054273,1084242,2.166133,...,7902793,15.788448,Pre:Cocktail,0.2767,0.42,22.460194,4.1,6.683051,3.6575,C2_Pre
26,D1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_D1_Pre_BR_292141.bam,Control,47371511,28971,47371511,1020863,2.155015,...,10255908,21.649949,Pre:Control,0.9491,0.40,12.573115,4.6,4.914221,6.6300,D1_Pre
27,D2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_D2_Pre_BR_206166.bam,Control,46912722,29100,46912722,1347793,2.872980,...,10607772,22.611717,Pre:Control,0.4732,0.34,26.722870,4.3,7.504336,4.2795,D2_Pre
28,E1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_E1_Pre_BR_293153.bam,Control,50558345,29206,50558345,1264149,2.500377,...,8728047,17.263316,Pre:Control,0.4270,1.24,19.938857,4.4,5.444510,2.8600,E1_Pre
29,E2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_E2_Pre_BR_207178.bam,Cocktail,52668637,29527,52668637,1179858,2.240153,...,8390096,15.929966,Pre:Cocktail,0.3234,0.59,20.472952,4.1,7.110272,3.0645,E2_Pre
30,F1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_F1_Pre_BR_294165.bam,Cocktail,48451403,29338,48451403,1189422,2.454876,...,8102350,16.722632,Pre:Cocktail,0.4397,0.58,10.086931,4.5,6.601610,3.1050,F1_Pre
31,F2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_F2_Pre_BR_208190.bam,Cocktail,50626012,29264,50626012,1530065,3.022290,...,8111235,16.021872,Pre:Cocktail,0.2933,1.07,15.529665,4.0,10.675028,5.5720,F2_Pre
32,G1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_G1_Pre_BR_295177.bam,Cocktail,52345902,29407,52345902,1655829,3.163245,...,7268950,13.886378,Pre:Cocktail,0.4627,1.22,16.315768,4.5,6.776144,3.3970,G1_Pre
33,G2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_G2_Pre_BR_209107.bam,Control,51293259,29283,51293259,1129648,2.202332,...,10198605,19.882934,Pre:Control,0.4253,0.40,33.918688,4.1,9.998550,4.5370,G2_Pre
34,H1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_H1_Pre_BR_296189.bam,Control,51799883,28767,51799883,1779780,3.435876,...,10292354,19.869454,Pre:Control,0.4743,0.50,13.499287,4.4,7.521159,3.7120,H1_Pre
35,H2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_H2_Pre_BR_210119.bam,Cocktail,50753892,29222,50753892,1356609,2.672916,...,10107321,19.914376,Pre:Cocktail,0.4448,0.51,18.661565,4.1,8.878745,2.9045,H2_Pre
36,I1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_I1_Pre_BR_201106.bam,Cocktail,46385254,29999,46385254,1212978,2.615008,...,7041935,15.181409,Pre:Cocktail,0.3217,1.34,21.096212,4.5,5.610401,2.8600,I1_Pre
37,I2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_I2_Pre_BR_211131.bam,Cocktail,49561052,29351,49561052,1284697,2.592150,...,10378392,20.940621,Pre:Cocktail,0.2805,0.55,27.346620,4.3,8.058199,3.7080,I2_Pre
38,J1,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_J1_Pre_BR_202118.bam,Control,52893287,29754,52893287,1128474,2.133492,...,10963227,20.727067,Pre:Control,0.5464,0.47,18.300000,4.9,7.679879,2.9045,J1_Pre
39,J2,Pre,/n/groups/kirschner/Will/BedRest/nfcore_rnaseq...,Pre_J2_Pre_BR_212143.bam,Control,49908866,29381,49908866,1236687,2.477890,...,8741068,17.514059,Pre:Control,0.2321,0.75,6.927000,4.4,9.234471,2.8600,J2_Pre

In [9]:
samples.to_csv(os.path.join(INPUT_DIR, "samples_star_rsem_tximport.csv"), index=False)

In [10]:
os.path.join(INPUT_DIR, "samples_star_rsem_tximport.csv")

'/n/groups/kirschner/Will/BedRest/samples_star_rsem_tximport.csv'